// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Account Registration', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Account Registration', async function() {
    await driver.get("https://moviesroom.pl/rejestracja/")
    await driver.manage().window().setRect({ width: 1920, height: 1080 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("123123")
    await driver.findElement(By.id("register")).click()
    await driver.findElement(By.id("passw1")).click()
    await driver.findElement(By.id("passw1")).sendKeys("Test")
    await driver.findElement(By.id("register")).click()
    await driver.findElement(By.id("email")).click()
    vars["email"] = await driver.executeScript("return Math.random().toString(36).substring(2,11) + \'@domain.com\'")
    await driver.findElement(By.id("email")).sendKeys(vars["email"])
    await driver.findElement(By.id("passw2")).click()
    await driver.findElement(By.id("passw2")).sendKeys("Test")
    await driver.findElement(By.id("user_consent_gdpr")).click()
    await driver.switchTo().frame(0)
    await driver.findElement(By.css(".recaptcha-checkbox-border")).click()
    await driver.switchTo().defaultContent()
    await driver.findElement(By.id("register")).click()
    await driver.executeScript("window.scrollTo(0,91)")
    await driver.findElement(By.id("username")).click()
    vars["username"] = await driver.executeScript("return Math.random().toString(36).substring(2,11)")
    await driver.findElement(By.id("username")).sendKeys(vars["username"])
    await driver.findElement(By.id("passw1")).click()
    vars["password"] = await driver.executeScript("return Math.random().toString(36).substring(2,11)")
    await driver.findElement(By.id("passw1")).sendKeys(vars["password"])
    await driver.findElement(By.id("passw2")).click()
    console.log("id=passw2")
    await driver.findElement(By.id("passw2")).sendKeys(vars["password"])
    await driver.findElement(By.id("entry")).click()
    await driver.switchTo().frame(0)
    await driver.findElement(By.css(".recaptcha-checkbox-border")).click()
    await driver.switchTo().defaultContent()
    await driver.findElement(By.id("register")).click()
  })
})
