// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Functionality of the Main Page', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Functionality of the Main Page', async function() {
    await driver.get("https://moviesroom.pl//")
    await driver.manage().window().setRect({ width: 1920, height: 1080 })
    await driver.findElement(By.css(".active .big > .thumb")).click()
    await driver.findElement(By.css("#menu-item-20544 img")).click()
    await driver.findElement(By.css(".subcategories > .cat-item-18 > a")).click()
    await driver.findElement(By.css("#menu-item-20544 img")).click()
    await driver.findElement(By.css(".cat-item-19:nth-child(2) > a")).click()
    await driver.findElement(By.css("#menu-item-20544 img")).click()
    await driver.findElement(By.css(".subcategories > .cat-item-30 > a")).click()
    await driver.findElement(By.css("#menu-item-20544 img")).click()
    await driver.findElement(By.css(".subcategories > .cat-item-32 > a")).click()
    await driver.findElement(By.css("#menu-item-20544 img")).click()
    await driver.findElement(By.css(".subcategories > .cat-item-32 > a")).click()
    await driver.findElement(By.css("#menu-item-20544 img")).click()
    await driver.findElement(By.css(".cat-item-33:nth-child(6) > a")).click()
    await driver.findElement(By.css("#menu-item-20544 img")).click()
    await driver.findElement(By.linkText("Dane osobowe")).click()
  })
})
