// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Personal Data Tab', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Personal Data Tab', async function() {
    await driver.get("https://moviesroom.pl/")
    await driver.manage().window().setRect({ width: 1920, height: 1080 })
    await driver.findElement(By.linkText("Dane osobowe")).click()
  })
})
