// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Redirection to the Instagram Page', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('Redirection to the Instagram Page', async function() {
    await driver.get("https://moviesroom.pl//")
    await driver.manage().window().setRect({ width: 1920, height: 1080 })
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css(".fa-instagram")).click()
    vars["win4582"] = await waitForWindow(2000)
    await driver.switchTo().window(vars["win4582"])
  })
})
